Fix raise exception from SubscriptionState.assign_from_subscribed
Raising `ValueError` from `SubscriptionState.assign_from_subscribed()`
always fails because there is used percent formatting of `TopicPartition`.
But `TopicPartition` is namedtuple with two elements and percent
formatting tries to unpack tuples, fails and raise exception:
TypeError: not all arguments converted during string formatting.
Converting to string first solves the issue.